### ISSUE TITLE
Failed to find MPU6050 chip

### ISSUE THREAD

**Issue by ZCB1208** [adafruit/Adafruit_MPU6050#11]
the new version MPU6050 has the different DEVICE_ID

Change the Macro in “Adafruit_MPU6050.h” File:
   #define MPU6050_DEVICE_ID 0x68 -> #define MPU6050_DEVICE_ID 0x98 
can solve the problem .

I don't think this is the best solution to solve it. so I just put it in Issues.

I try the solution (add code to main.ino):

    #ifdefine MPU6050_DEVICE_ID 
    #undefine MPU6050_DEVICE_ID 
    #define MPU6050_DEVICE_ID 0x98
    #endif

but it did not work.

**Comment by caternuson** [comment]
Where did you source the MPU6050's with `0x98` device IDs?

**Comment by ZCB1208** [comment]
> Where did you source the MPU6050's with `0x98` device IDs?

From “https://www.taobao.com”  .  I come from China .

**Comment by caternuson** [comment]
It's probably not a MPU6050.
