### ISSUE TITLE
Example for motion detection interrupt

### ISSUE THREAD

**Issue by ShaymonAlvarez** [adafruit/Adafruit_MPU6050#12]
Hi! Is there any complete example for getting motion detection interrupt using this library? I noticed that someone has already implemented on the pull request but the same guy didn't give us a complete valid example, just a small snippet. I tried to use this snippet but I haven't got success on achieving this detection.

**Comment by gabrielcsapo** [comment]
https://github.com/adafruit/Adafruit_MPU6050/pull/6 is open and hopefully can be merged to fix this!
