### ISSUE TITLE
WDT trigger on ESP32C3

### ISSUE THREAD

**Issue by lifankohome** [adafruit/Adafruit_MPU6050#13]
I'm using a ESP32C3 board, and the program will stop for about 30min, and WDT got trigger.

The same program works fine on ESP8266.

**Comment by gabrielcsapo** [comment]
can you share code? I have been running it for well over 30 minutes on my esp32-c3 and haven't gotten the same issue.

**Comment by caternuson** [comment]
Closing. Can reopen if example sketch demonstrating issue can be provided.
