### ISSUE TITLE
Code of Conduct link is broken

### ISSUE THREAD

**Issue by guiescuissato** [adafruit/Adafruit_MPU6050#15]
The link to the code of conduct is leading to a broken page. Is there a new link that it should point to?

The current link is this:
https://github.com/adafruit/Adafruit_MPU6050/blob/master/CODE_OF_CONDUCT.md%3E

Is this the correct link?
https://github.com/adafruit/Adafruit_MPU6050/blob/86e65d01e5dc4529d4f8a362f491949c322fb1df/code-of-conduct.md

**Comment by kattni** [comment]
Close! The correct link is closer to the first, but minus an errant `>` at the end, and `code-of-conduct` as the formatting for the name. I fixed the link. Thanks for the report!
