### ISSUE TITLE
No .h headers in latest release - throws error

### ISSUE THREAD

**Issue by videobuff** [adafruit/Adafruit_MPU6050#16]
- Arduino board:  **ESP32E**

- Arduino IDE version:  **1.8.19**
 **LIST REPRO STEPS BELOW**
When i try to add the libary to the Arduio IDE, it throws an error that .h files are not found. The text in the picture is in dutch.

![Schermafbeelding 2022-02-23 om 13 54 43](https://user-images.githubusercontent.com/3132953/155324224-4287f1c0-cd26-47f1-8af1-c7c964dbb437.jpg)

Then i downloaded the sirectory as a zip file, and installed it through the sketch. It told me all was ok , but after compilation igot this message: The first part in dutch tells me unvalid library found. And again, noheaders

Leaving...
Hard resetting via RTS pin...
Ongeldige bibliotheek gevonden in /Users/erikschott/Documents/Arduino/libraries/Adafruit_MPU6050: no headers files (.h) found in /Users/erikschott/Documents/Arduino/libraries/Adafruit_MPU6050

**Comment by caternuson** [comment]
Just did a test install here and it brought in all the files as expected:

![Screenshot from 2022-02-23 07-09-06](https://user-images.githubusercontent.com/8755041/155347274-97356246-01cb-4fd6-a33f-fa92da252070.png)

![Screenshot from 2022-02-23 07-09-15](https://user-images.githubusercontent.com/8755041/155347309-60b5d004-198a-4076-b08a-8dab5cc3cac8.png)

```
~/Arduino/libraries/Adafruit_MPU6050$ ls
Adafruit_MPU6050.cpp  Adafruit_MPU6050.h  assets  code-of-conduct.md  examples  library.properties  license.txt  README.md
```

Try manually deleting the library folder and reinstalling again via Library Manager. Does the issue repeat?
