### ISSUE TITLE
Bias cancellation procedure is missing

### ISSUE THREAD

**Issue by FxIII** [adafruit/Adafruit_MPU6050#2]
MPU6050 suffers from small gyro biases that make it difficult to compute the orientation in the absence of a compass reference.

[This application note](https://www.digikey.jp/Web%20Export/Supplier%20Content/invensense-1428/pdf/invensense-mpu-hardware-offset.pdf) shows a possible procedure to the problem. 

I also found a complete implementation [here](https://os.mbed.com/teams/Seeed/code/eMPL_MPU6050/docs/6aedb937cb38/inv__mpu_8c_source.html#). 

I think a proper integration of these procedures in this library is necessary to make it fully usable.

**Comment by ladyada** [comment]
hi we have a guide here on calibration
https://learn.adafruit.com/adafruit-sensorlab-gyroscope-calibration
and this guide can be used as well - 
https://learn.adafruit.com/how-to-fuse-motion-sensor-data-into-ahrs-orientation-euler-quaternions
if you'd like to submit an example as a PR it would be welcome :)
