### ISSUE TITLE
Can esp32 not be used?

### ISSUE THREAD

**Issue by bbhxwl** [adafruit/Adafruit_MPU6050#24]
![B$)73~S2V4WW6GSZX0RVXQ3](https://user-images.githubusercontent.com/26525599/179390130-cd9f6af4-057d-4aae-91d0-731e1a25bcda.png)

![C6N{TVUWDJQC~@FO` 7HE25](https://user-images.githubusercontent.com/26525599/179390119-fb10a789-2ca3-4f7f-b47b-c76c3b51fca3.jpg)
![7D2299B)F2ULRF` @CILI{R](https://user-images.githubusercontent.com/26525599/179390125-794e3bc9-73bc-4864-aba3-675a20d5302d.png)

**Comment by asjdf** [comment]
Try to add `Wire.begin(21, 22);` before the `mpu.begin()`.
I think this problem is worth a PR.

**Comment by caternuson** [comment]
The `basic_readings` example sketch runs fine here on a Feather ESP32.
```
MPU6050 Found!
Accelerometer range set to: +-8G
Gyro range set to: +- 500 deg/s
Filter bandwidth set to: 21 Hz

Acceleration X: 6.34, Y: -7.23, Z: -4.28 m/s^2
Rotation X: -0.05, Y: 0.01, Z: -0.01 rad/s
Temperature: 23.15 degC

Acceleration X: 6.33, Y: -7.23, Z: -4.28 m/s^2
Rotation X: -0.05, Y: 0.01, Z: -0.01 rad/s
Temperature: 23.27 degC

Acceleration X: 6.34, Y: -7.24, Z: -4.30 m/s^2
Rotation X: -0.05, Y: 0.01, Z: -0.01 rad/s
Temperature: 23.34 degC
```

Please post in the forums with photos of your setup:
https://forums.adafruit.com/
