### ISSUE TITLE
Too many dependencies?

### ISSUE THREAD

**Issue by svrooij** [adafruit/Adafruit_MPU6050#31]
These dependencies are only needed for one of the samples and not for using the actual sensor. 
It has nothing to do with graphics or controlling some mono screen.

```
- [Adafruit GFX Library](https://github.com/adafruit/Adafruit-GFX-Library)
- [Adafruit SSD1306](https://github.com/adafruit/Adafruit_SSD1306)
```

**Comment by caternuson** [comment]
Correct. But including all the required dependencies allows all the examples to work once the library is installed.

Leaving them out would just lead to issues be opened with "Example XYZ does not work".

**Comment by svrooij** [comment]
I tried using it in ESPhome and then it starts downloading all the dependencies specified in the library file.

why not put a comment line in the sample “to control the screen you need to install library x and y” and keep the main library file clean of things that are not used by the library.

**Comment by caternuson** [comment]
No one would read it. These things have been tried. It's a trade off.
