### ISSUE TITLE
Multiple MPUs in the same code?

### ISSUE THREAD

**Issue by njordan77** [adafruit/Adafruit_MPU6050#4]
We try to use two MPU650 in parallel @UNO in the same code. 
Generally I2C scanner shows both of them with their addresses.

This does not seem to work:

Adafruit_MPU6050 accelgyroIC1(0x68);
Adafruit_MPU6050 accelgyroIC2(0x69);

Any idea what we did wrong?
Thanks

**Comment by ladyada** [comment]
yes in begin()
https://github.com/adafruit/Adafruit_MPU6050/blob/master/Adafruit_MPU6050.h#L191
