### ISSUE TITLE
Where are the docs?

### ISSUE THREAD

**Issue by matdombrock** [adafruit/Adafruit_MPU6050#9]
In the readme I see that it mentions that the docs are generated with Doxygen and I see the links to learn about Doxygen but where are the *actual docs* for this project located?

**Comment by ladyada** [comment]
https://github.com/adafruit/Adafruit_MPU6050/tree/gh-pages
https://adafruit.github.io/Adafruit_MPU6050/html/class_adafruit___m_p_u6050.html

**Comment by matdombrock** [comment]
Thanks, I might have missed something but this is very hard to find.

Maybe it these links should go in the readme?

**Comment by ladyada** [comment]
sure, please submit a PR for the readme if you can :)
